### ISSUE TITLE
withEntryで配列が扱えない

### ISSUE THREAD

**Issue by FujiHaruka** [the-labo/the-scene-mixins#3]
@okunishinishi 
配列の再セットがうまくいかない。

落ちるテスト： https://github.com/realglobe-Inc/the-scene-mixins/blob/94bf303442e0873897eea2f1e247287176000343/test/withEntryTest.js

抜き出すとこれ。

```js
    obj.setEntry({
      a: [{ i: 1 }, { i: 2 }]
    })
    obj.setEntry({
      a: [{ i: 1 }]
    })
    equal(obj.getEntry().a.length, 1)
```

要するに `objnest` の expand / flatten を内部で使っているからなのだけど、setEntry()するときに flatten する必要性ってあるんですかね？（このコードを読むだけではわからなかった）

**Comment by okunishinishi** [comment]
ないかも。。。ちょっと見てます

もともとhtmlのformが配列とかサポートしてないのでflattenが必要だった気がしなくもないですがここで必要かどうかはだいぶ怪しいかも

**Comment by okunishinishi** [comment]
とりあえずテストを通るようにはした。

https://github.com/the-labo/the-scene-mixins/commit/768c6fe7417338f00e28fb5707d02e230c65a9be#diff-8a6109dd598db55e220673e32460e5b8

**Comment by FujiHaruka** [comment]
配列が扱えるようになったのでこの issue は close
